### ISSUE TITLE
Chat window in /destinychat 

### ISSUE THREAD

**Issue by Biscophan** [ILiedAboutCake/OverRustle#28]
Chat window in /destinychat is appearing beneath the strim icons. Here are a few screenshots at different zoom percentages (100%, 110%, 125%) to show how the chat window moves around on the page. My apologies if I'm not submitting this issue in the correct format..

http://imgur.com/93ARy8X,ZheXFCm,APet6kH#0
http://i.imgur.com/MLoNCJ0.png

**Comment by hayksaakian** [comment]
a recent pull should fix this, see #34

**Comment by ILiedAboutCake** [comment]
fixed  https://github.com/ILiedAboutCake/OverRustle/commit/c0d6e61f4a7048edc6abc44ef7cbc2768db9b184
