### ISSUE TITLE
sessions are getting mixed up

### ISSUE THREAD

**Issue by hayksaakian** [ILiedAboutCake/OverRustle#47]
http://imgur.com/LG9lLrJ

http://i.imgur.com/yLzKcrH.png

https://imgur.com/AcStawx

Is nginx caching something it should not be caching? what's going on here...

**Comment by hayksaakian** [comment]
when a user who unintenionally picked up a my session tried to change something:

http://imgur.com/wJRyCt2

**Comment by hayksaakian** [comment]
some got access errors in the frontend when trying to change

http://i.imgur.com/2MRe3hN.png

others got errors from node (stack traces)

http://imgur.com/x823G99 (linked earlier)

**Comment by hayksaakian** [comment]
this is difficult to reproduce in development...

**Comment by hayksaakian** [comment]
http://imgur.com/J1UqpZi another report from the wild

**Comment by ILiedAboutCake** [comment]
Issue was fixed by disabling caching at nginx via https://github.com/ILiedAboutCake/OverRustle/commit/bca4e7af5340977bd8449922b1e927f1586c088c
