### ISSUE TITLE
Chat not loading on Chrome with third-party blocking enabled

### ISSUE THREAD

**Issue by Asa-1** [ILiedAboutCake/OverRustle#49]
The (optional) policy to block third-party cookies and site-data seems to throw to security errors when loading the chat on Overrustle.

Tested with:
- Chromium - Version 48.0.2564.82 Built on Ubuntu 14.04, running on elementary OS 0.3.2 (64-bit)
- Chromium - Version 50.0.2634.0 (Windows 7)
- Chrome - Version 48.0.2564.103 m (64-bit) (Windows 7)

Console Log:
```
connected []
approved to watch *******
got rustlers 282
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
	(anonymous function) @ ui.js:245
	(anonymous function) @ ui.js:266
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
	(anonymous function) @ hints.js:3
	(anonymous function) @ hints.js:120
Uncaught TypeError: $(...).ChatGui is not a function
	(anonymous function) @ chat:259
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
	(anonymous function) @ ui.js:4
	j @ jquery-1.11.3.min.js:2
	k.fireWith @ jquery-1.11.3.min.js:2
	m.extend.ready @ jquery-1.11.3.min.js:2
	J @ jquery-1.11.3.min.js:2
```

**Setting an exception for "www.destiny.gg" in the cookie settings solves this issue.**

I understand it looks more like a feature than a bug, but is there something that can be done?

**Comment by ILiedAboutCake** [comment]
We embed https://destiny.gg/embed/chat from the dgg servers. No reason to re-invent the wheel, I will look into this soon™

**Comment by ILiedAboutCake** [comment]
Can't be bothered to do anything about this. It's a feature™

**Comment by hayksaakian** [comment]
given that destiny.gg is a third party relative to overrustle.com i would presume that your chrome feature is working as intended, because it's blocking the 3rd party embed. right?
