### ISSUE TITLE
support hitbox vods?

### ISSUE THREAD

**Issue by hayksaakian** [ILiedAboutCake/OverRustle#55]
thoughts?

do they even have a proper embed code for vods

**Comment by KenanY** [comment]
Couldn't find any documentation but clicking "popout" whilst watching a VOD yields a URL like: `www.hitbox.tv/embedvideo/{id}` i.e. <http://www.hitbox.tv/embedvideo/825445>

**Comment by hayksaakian** [comment]
nice! iframing that url works, ill work on a update for this.

@ILiedAboutCake what do you think?

super basic demo here: http://scratchpad.io/nippy-bead-4341

**Comment by KenanY** [comment]
This is done, right? https://github.com/ILiedAboutCake/OverRustle/commit/912e4de0f250dd012f3901970e26f80ab7646943

**Comment by hayksaakian** [comment]
yes sir!
